const cartTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  SAVE_USER_CART: 'SAVE_USER_CART'  // FOR SAVING CART ITEMS TO USERS
}

export default cartTypes