const feedTypes = {
    LIKE_HELPFUL_VIDEO: 'LIKE_HELPFUL_VIDEO',
    DISLIKE_HELPFUL_VIDEO: 'DISLIKE_HELPFUL_VIDEO',
    USERS_LIKES_STATE_CHANGE: 'USERS_LIKES_STATE_CHANGE',
    CLEAR_DATA: 'CLEAR_DATA',
    STACK_VIDEOS:'STACK_VIDEOS',
    USERS_LIKES_STATE_CHANGE:'USERS_LIKES_STATE_CHANGE'

}

export default feedTypes